-- Baseline Session Pro backend schema. This is the launch schema; post-launch changes go in new,
-- ascii-later NNN_* migrations (never edit this file once it has shipped to a database with real
-- data). Tables are ordered so foreign-key targets exist before their referrers.

-- The user identity anchor. master_pkey (the account's Ed25519 public key) lives ONLY here; everything
-- else references a user by the surrogate `id`.
CREATE TABLE IF NOT EXISTS users (
    -- BY DEFAULT (not ALWAYS) so the entitlement path can pre-allocate an id to satisfy the circular
    -- users<->generations FK in one transaction (see current_generation_id below).
    id                           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_pkey                  BYTEA       NOT NULL UNIQUE CHECK (octet_length(master_pkey) = 32),
    -- The user's active generation (entitlement epoch). NOT NULL — every user always has one. The FK is
    -- added after `generations` exists (circular ref) and is DEFERRABLE so a new user + its first
    -- generation can be inserted together in one transaction.
    current_generation_id        BIGINT      NOT NULL,
    expires_at                   TIMESTAMPTZ NOT NULL,
    grace_period                 INTERVAL    NOT NULL DEFAULT '0'::interval,
    auto_renewing                BOOLEAN     NOT NULL DEFAULT FALSE,
    -- NULL = no refund requested.
    refund_requested_at          TIMESTAMPTZ
    -- (No account-id columns here: the provider account ids are pure functions of master_pkey — see
    -- {google,apple}_obfuscated_account_id_from_master_pkey — and are stored on `payments` only, where
    -- they serve as the auto-redeem lookup key. Persisting them on the user row was redundant.)
);

-- Enumerated value sets. The code string is the canonical value used in Python, on the wire, and in the
-- signed request hashes, so it is the PRIMARY KEY (no surrogate id): children FK the code directly, and
-- a new provider/plan is an additive INSERT (never an ALTER TYPE). Seeds are idempotent so re-applying
-- the baseline against a pre-ledger database is a no-op.
CREATE TABLE IF NOT EXISTS payment_providers (
    code TEXT PRIMARY KEY
);
INSERT INTO payment_providers (code) VALUES ('google_play'), ('app_store'), ('rangeproof')
    ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS pro_plans (
    code TEXT PRIMARY KEY
);
INSERT INTO pro_plans (code) VALUES ('1m'), ('3m'), ('1y')
    ON CONFLICT (code) DO NOTHING;

-- A payment is ingested UNREDEEMED (user_id NULL) before any identity is attached; at redemption the
-- master_pkey becomes known, its users row is upserted, and user_id is backfilled here.
CREATE TABLE IF NOT EXISTS payments (
    id                                BIGINT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id                           BIGINT  REFERENCES users(id),   -- NULL until redeemed
    -- No `status` column: it is derived from the timestamps below (redeemed/revoked/expiry) — see
    -- backend.derive_payment_status. redeemed_at IS NULL = unredeemed; revoked_at IS NOT NULL = revoked;
    -- now >= expires_at = expired.
    plan                              TEXT        NOT     NULL REFERENCES pro_plans(code),
    payment_provider                  TEXT        NOT     NULL REFERENCES payment_providers(code),
    auto_renewing                     BOOLEAN     NOT     NULL DEFAULT FALSE,
    -- When this payment (billing cycle) was purchased at the provider (Apple purchaseDate / Google
    -- event ts). NOT when we witnessed it.
    purchased_at                      TIMESTAMPTZ NOT     NULL,

    redeemed_at                       TIMESTAMPTZ,                    -- NULL until redeemed
    expires_at                        TIMESTAMPTZ NOT     NULL,
    grace_period                      INTERVAL    NOT NULL DEFAULT '0'::interval,
    platform_refund_expires_at        TIMESTAMPTZ NOT     NULL,
    revoked_at                        TIMESTAMPTZ,                    -- NOT NULL once revoked

    -- NULL = no refund requested.
    refund_requested_at               TIMESTAMPTZ

    -- Provider-specific identifiers do NOT live here — they're in the per-provider *_payment_details
    -- tables below (one row, keyed by payment_id, in exactly the table matching payment_provider). That
    -- keeps this table provider-agnostic: a new provider is a new focused detail table, not another
    -- batch of nullable columns crudding up `payments`.
);

CREATE INDEX IF NOT EXISTS payments_user_id_idx    ON payments (user_id) WHERE user_id IS NOT NULL;  -- owner lookups + PAYMENTS_FROM join
CREATE INDEX IF NOT EXISTS payments_expires_at_idx ON payments (expires_at);                         -- daily expiry sweep

-- Per-provider payment identifiers (item 15 follow-up). Exactly one of these has a row for a given
-- payment, in the table matching payments.payment_provider; payment_id is the PK *and* FK, so the 1:1 is
-- structural and the detail row is pruned with its payment (ON DELETE CASCADE). Typed columns with real
-- NOT NULLs replace the old sparse provider columns on `payments`.
CREATE TABLE IF NOT EXISTS google_play_payment_details (
    payment_id            BIGINT PRIMARY KEY REFERENCES payments(id) ON DELETE CASCADE,
    payment_token         TEXT  NOT NULL,
    order_id              TEXT  NOT NULL,
    obfuscated_account_id BYTEA NOT NULL CHECK (octet_length(obfuscated_account_id) = 32)
);
-- Auto-redeem matches (payment_token, order_id, obfuscated_account_id); revocation matches payment_token.
CREATE INDEX IF NOT EXISTS google_play_payment_details_token_idx ON google_play_payment_details (payment_token);

CREATE TABLE IF NOT EXISTS app_store_payment_details (
    payment_id           BIGINT PRIMARY KEY REFERENCES payments(id) ON DELETE CASCADE,
    original_tx_id       TEXT NOT NULL,
    tx_id                TEXT NOT NULL,
    web_line_order_tx_id TEXT NOT NULL,
    app_account_token    TEXT NOT NULL
);
-- Auto-redeem matches (tx_id, app_account_token); revocation matches original_tx_id.
CREATE INDEX IF NOT EXISTS app_store_payment_details_tx_id_idx       ON app_store_payment_details (tx_id);
CREATE INDEX IF NOT EXISTS app_store_payment_details_original_tx_idx ON app_store_payment_details (original_tx_id);

CREATE TABLE IF NOT EXISTS rangeproof_payment_details (
    payment_id  BIGINT PRIMARY KEY REFERENCES payments(id) ON DELETE CASCADE,
    order_id    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS rangeproof_payment_details_order_id_idx ON rangeproof_payment_details (order_id);

-- A generation is a user's signed-entitlement epoch (the aggregate of their stacked payments), NOT
-- per-payment and NOT per-proof. `token` is a random 32-byte value embedded verbatim in proofs and the
-- revocation list (the wire `revocation_tag`). A revocation IS `revoked_at` being set; the served
-- revocation list is the rows with revoked_at set, within the retention window.
CREATE TABLE IF NOT EXISTS generations (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ON DELETE CASCADE so pruning an orphaned user (no remaining payments) also removes its generations;
    -- the circular users.current_generation_id FK is DEFERRABLE, so the pair drops cleanly at COMMIT.
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      BYTEA       NOT NULL UNIQUE CHECK (octet_length(token) = 32),
    issued_at  TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ                                    -- NULL = live; set = revoked at this instant
);
CREATE INDEX IF NOT EXISTS generations_user_id_idx    ON generations (user_id);
-- The served revocation list scans only revoked rows; the daily sweep prunes long-past ones.
CREATE INDEX IF NOT EXISTS generations_revoked_at_idx ON generations (revoked_at) WHERE revoked_at IS NOT NULL;

-- The circular back-reference: users.current_generation_id -> generations.id. DEFERRABLE INITIALLY
-- DEFERRED so it's validated at COMMIT, letting a new user (inserted first, pointing at a not-yet-
-- existing generation) and that generation be created together in one transaction.
ALTER TABLE users ADD CONSTRAINT users_current_generation_fk
    FOREIGN KEY (current_generation_id) REFERENCES generations(id) DEFERRABLE INITIALLY DEFERRED;

-- App-global singletons as a key/value store with real column types. One row per global (the key is
-- the PK, so the "exactly one of each" property is structural — no unconstrained-singleton table).
-- Exactly one typed value slot is populated per row; add a new type by adding a column (e.g. text_val,
-- bool_val) + extending the CHECK, no DDL-to-widen-a-row.
CREATE TABLE IF NOT EXISTS globals (
    key       TEXT PRIMARY KEY,
    int_val   BIGINT,
    bytes_val BYTEA,
    ts_val    TIMESTAMPTZ,
    CHECK (num_nonnulls(int_val, bytes_val, ts_val) = 1)
);
-- Seed the singletons (static values, so plain SQL — idempotent like the enum seeds above).
INSERT INTO globals (key, int_val) VALUES ('revocation_ticket', 0)
    ON CONFLICT (key) DO NOTHING;
INSERT INTO globals (key, ts_val)  VALUES ('apple_notification_checkpoint_at', 'epoch'::timestamptz)
    ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS apple_notification_uuid_history (
    uuid              TEXT PRIMARY KEY,
    expires_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS google_notification_history (
    message_id        TEXT PRIMARY KEY,   -- Pub/Sub message id: opaque STRING, never a number (item 11)
    handled           BOOLEAN NOT NULL DEFAULT FALSE,
    payload           TEXT,
    expires_at        TIMESTAMPTZ NOT NULL
);
-- The startup drain reads `WHERE NOT handled`; a partial index keeps that off a full seq-scan as the
-- buffer grows (item 10).
CREATE INDEX IF NOT EXISTS google_notification_history_unhandled ON google_notification_history (message_id) WHERE NOT handled;

-- `payment_id` here is the provider's tx-id STRING (Apple original_tx_id / Google payment_token), NOT
-- payments.id — there is deliberately no FK: payments stores these under provider-specific typed columns
-- (see has_user_error_from_master_pkey_tx's provider-branched join), so no single key matches. The
-- (provider, tx-id) pair is the natural identity, declared as the PK (was a stray UNIQUE); ordered
-- provider-first to match every lookup (always by both columns) and the INSERT column order.
CREATE TABLE IF NOT EXISTS user_errors (
    payment_provider   TEXT NOT NULL REFERENCES payment_providers(code),
    payment_id         TEXT NOT NULL,
    errored_at         TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (payment_provider, payment_id)
);

-- Single-row aggregate view of table counts for ad-hoc operator inspection: `SELECT * FROM db_stats`.
CREATE OR REPLACE VIEW db_stats AS
SELECT
    (SELECT COUNT(*) FROM users)                                                     AS users,
    (SELECT COUNT(*) FROM payments)                                                  AS payments,
    (SELECT COUNT(*) FROM payments WHERE redeemed_at IS NULL AND revoked_at IS NULL) AS unredeemed_payments,
    (SELECT COUNT(*) FROM generations)                                               AS generations,
    (SELECT COUNT(*) FROM generations WHERE revoked_at IS NOT NULL)                  AS revocations,
    (SELECT COUNT(*) FROM user_errors)                                               AS user_errors,
    (SELECT COUNT(*) FROM google_notification_history)                               AS google_notifications,
    (SELECT COUNT(*) FROM apple_notification_uuid_history)                           AS apple_notifications;

-- Trigger: bump the revocation_ticket global whenever a generation is newly revoked (client cache-gen
-- stamp). Add-only — it fires on the NULL->non-NULL transition of revoked_at, never on prune-removal of
-- a long-stale revoked generation (a stale entry going away is not an actionable event for clients).
CREATE OR REPLACE FUNCTION increment_revocation_ticket()
RETURNS TRIGGER AS '
BEGIN
    UPDATE globals SET int_val = int_val + 1 WHERE key = ''revocation_ticket'';
    RETURN NEW;
END;
' LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS increment_revocation_ticket_on_revoke ON generations;
CREATE TRIGGER increment_revocation_ticket_on_revoke
    AFTER UPDATE OF revoked_at ON generations
    FOR EACH ROW
    WHEN (OLD.revoked_at IS NULL AND NEW.revoked_at IS NOT NULL)
    EXECUTE FUNCTION increment_revocation_ticket();

-- Enforce the terminal invariant in the DB, not just in code: a revocation is permanent, so once
-- `revoked_at` is set it can never be changed or cleared (no un-revoke, no re-timestamp). Can't be a
-- CHECK (those can't see the OLD row), so it's a BEFORE-UPDATE guard that raises on any real change to
-- an already-set value (a same-value rewrite is a harmless no-op and allowed).
CREATE OR REPLACE FUNCTION forbid_revoked_at_change()
RETURNS TRIGGER AS '
BEGIN
    RAISE EXCEPTION ''generations.revoked_at is terminal: it cannot be changed or cleared once set (id=%)'', OLD.id;
END;
' LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS generations_revoked_at_is_terminal ON generations;
CREATE TRIGGER generations_revoked_at_is_terminal
    BEFORE UPDATE OF revoked_at ON generations
    FOR EACH ROW
    WHEN (OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at)
    EXECUTE FUNCTION forbid_revoked_at_change();
